### PR TITLE
Add new Smile branded icons for uploader

### PR DESCRIPTION
**Pull request by tomnez**
Swapping out the upload icons for some icons that align more with Smile branding.

"File" icon and "Image' icon -

file-uploader

image-uploader

### CODE REVIEW

**Comment by tomnez** [comment]
@vladucu is overwriting in `admin` preferred here? `ember-smile-polaris` is specifically created to add our own custom changes/overrides to `ember-polaris` so that's why I did it here.

I'm not opposed to moving it, just curious as to the reasoning behind it.

**Comment by tomnez** [comment]
The old image was 92x90 instead of 100x100, here's a before and after with the new icon from Lichen -

**Before:**

before

**After:**

after

**Comment by vladucu** [comment]
@tomnez is this waiting on anything?

**Comment by tomnez** [comment]
@vladucu whoa blast from the past.. no I don't believe so. I'll merge and do a round of updated releases today.

**Pull request merged**
