### PR TITLE
Support yielded block in empty search results component

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**

### CODE REVIEW

**Comment by andrewpye** [comment]
@sivakumar-kailasam what's the use case for this?

**Comment by sivakumar-kailasam** [comment]
Screenshot 2019-07-12 at 5 39 38 PM

The subtext contains a cta, I felt it was better handled with a yielded block in case we'll need to include more than 1 link as a part of the text in the future.

**Comment by andrewpye** [comment]
How do you feel about taking advantage of composability and our `render-content` helper and instead of `yield`ing, change `description` to accept a component definition and render it with `{{render-content description}}`? That way we can save `yield` for future cases if we need to make more drastic changes to an empty search result instance 🤔

**Comment by sivakumar-kailasam** [comment]
Correct me if I'm wrong about this but the following block which this component has can't be replaced with a `{{render-content description}}` since the rendered content might not expect to be inside a subdued `polaris-text-style` component & for the sake of using `render-content` we'll have to change existing invocation of this component. This is a typical case of using yielding content & I understand we have `render-content` for cases like this, but it feels like we're trying to use it here mostly since we have it.

```
{{#if description}}
    {{#stack.item}}
      {{#polaris-text-style variation="subdued"}}
        <p>{{description}}</p>
      {{/polaris-text-style}}
    {{/stack.item}}
  {{/if}}```

But if there's a better way around this, do let me know.

**Comment by andrewpye** [comment]
>the rendered content might not expect to be inside a subdued `polaris-text-style` component

We'd be passing in components specifically to be rendered in the description, so we'd know in advance that what we were passing would be rendered subdued. Alternatively we can replace your new `has-block` check with a test for a component definition and `render-content` instead of `yield`ing inside that conditional, but I think that's unnecessary.

>for the sake of using `render-content` we'll have to change existing invocation of this component

I'm curious about why we'd have to change existing invocations - `render-content` is smart and detects if the passed content is a string, and just renders that string in that case. So `@description="My description"` and `@description={{component "my-description-component"}}` will both Just Work™️ 🤔 

>it feels like we're trying to use [`render-content`] here mostly since we have it

Not my intention - `yield` is more limited than composable components:

- you can only ever render one yielded block, meaning that if it's used to allow customising a single piece of text, you lose the option to allow yielding as a means of customising e.g. a bigger chunk of content in the outer component's template - in this case, maybe down the line we'll want to be able to render something completely different than the image/title/description stack this component currently renders; if we've already used `yield` just to replace the `description`, we've lost the ability to support that larger-scale customisation without changing the component's spec and forcing updates of existing block usages;

- block usage to replace a single small portion of a component's template is less obvious to developers using the component - personally if I wanted to customise the description on this component, I'd be more likely to just try passing a component definition as the existing `description` property, rather than realising that I need to instead invoke the component in block format to achieve my objective.

I have other reasons but these are the main ones; I'd say that given that just switching `{{description}}` for `{{render-content description}}` at this point a) meets our needs, b) keeps the interface for the component the same as all current usages, and b) allows a greater degree of future customisations should we need them, it seems like our best choice at this point 🤷‍♂

**Comment by sivakumar-kailasam** [comment]
for anyone following along, `render-content` does seem to cover all bases in this scenario, so we're proceeding with it :)

**Pull request merged**
